### PR TITLE
chore: upgrade ajv to latest released version 8

### PR DESCRIPTION
**Pull request by ZigaStrgar**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

---

Updated `ajv` dependency to latest [release](https://github.com/ajv-validator/ajv/releases/tag/v8.0.0).

### CODE REVIEW

**Comment by Fdawgs** [comment]
Looks good to me! 😊

**Review by Fdawgs — APPROVED** [review]

**Review by climba03003 — APPROVED** [review]

**Review by L2jLiga — APPROVED** [review]
LGTM

**Review by RafaelGSS — APPROVED** [review]
LGTM. Is it a breaking change on `fastify@3` users, right? Should be released as major?

**Comment by ZigaStrgar** [comment]
I've tried to prepare an update for `fluent-json-schema` and `fastify` as they are running on `v6`, but there was still `ajv-keywords` and `ajv-formats` updates missing to support `v8`. I will try to provide an updates over the week.

**Comment by climba03003** [comment]
> 
> 
> I've tried to prepare an update for `fluent-json-schema` and `fastify` as they are running on `v6`, but there was still `ajv-keywords` and `ajv-formats` updates missing to support `v8`. I will try to provide an updates over the week.

`fastify` is moving `ajv` out of it's core to provide more flexibility. So, you do not need to update it for `fastify`.
Read More: https://github.com/fastify/fastify/issues/2742 and https://github.com/fastify/ajv-compiler/pull/1

**Comment by ZigaStrgar** [comment]
> `fastify` is moving `ajv` out of it's core to provide more flexibility. So, you do not need to update it for `fastify`.
> Read More: [fastify/fastify#2742](https://github.com/fastify/fastify/issues/2742) and [fastify/ajv-compiler#1](https://github.com/fastify/ajv-compiler/pull/1)

Awesome, thanks for the info!

**Comment by mcollina** [comment]
This could land as we are already drifting from Fastify own ajv version.

**Pull request merged**
