### PR TITLE
chore: add expandEnv to typescript and README

### PR DESCRIPTION
**Pull request by jmealo**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

This adds the `expandEnv` option to the Typescript definition and each example in the `README.md` for consistency.

I upgraded AJV to 8 and when I noticed tests broke based on changed output, it seemed like we should maybe make this a semver major change? If it broke our tests; it could break other folks? The behavior hasn't changed, but, output certainly has.

### CODE REVIEW

**Comment by RafaelGSS** [comment]
The AJV8 is being treated in #51. Please, let only `expandEnv` addiction in this PR.

**Review by RafaelGSS — CHANGES_REQUESTED** [review]
The AJV8 is being treated in #49 . Please, let only `expandEnv` addiction in this PR.

**Comment by jmealo** [comment]
@RafaelGSS: Removed AJV 8 changes.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by L2jLiga — APPROVED** [review]
LGTM

**Review by mcollina — CHANGES_REQUESTED** [review]
could you add a few assertions for these types?

**Comment by mcollina** [comment]
See https://github.com/fastify/env-schema/blob/master/test/types/types.test.ts

**Comment by climba03003** [comment]
close in favor of #86

**Pull request closed without merging**
