### PR TITLE
feat: :label: add typing

### PR DESCRIPTION
**Pull request by climba03003**
Add typing for https://github.com/fastify/fastify-env/issues/69 to reflect.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
Fail because of dependencies. 
Should this plugin move to GitHub actions? and also remove support for node 6 and node 8?

**Comment by Eomm** [comment]
> Should this plugin move to GitHub actions? and also remove support for node 6 and node 8?

Yes, we should revamp the dependencies and drop node at EOL stage in another PR before merging this one
Then we can bump a major 👍

**Comment by climba03003** [comment]
> 
> 
> > Should this plugin move to GitHub actions? and also remove support for node 6 and node 8?
> 
> Yes, we should revamp the dependencies and drop node at EOL stage in another PR before merging this one
> Then we can bump a major 👍

I have created the related PR #15 , please check it. Thanks.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by Eomm — APPROVED** [review]

**Pull request merged**
