### PR TITLE
add preprocess

### PR DESCRIPTION
**Pull request by mhf-ir**
Add preprocess for environment variable for ARRAY, OBJECT and custom preprocess

### CODE REVIEW

**Comment by mhf-ir** [comment]
> Can you check if you could implement the same feature just by leveraging some of the awesome Ajv keyword API? https://github.com/epoberezkin/ajv#defining-custom-keywords
> 
> I think we should be able to define arrays as `,` or `;` separated lists in that way.

I will try. i use colon by simple PATH universal POSIX env variable. It's use `:` for for array, but as you say,
```bash
echo $PATH
/home/sweb/.local/bin:/home/sweb/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by francisbrito** [comment]
Hello,

Thanks for proposing this change. I happen to need this functionality for a personal project and would like to contribute to this PR if possible.

@mhf-ir is it OK if I have a look at this?

**Comment by mhf-ir** [comment]
@francisbrito If course, 
sorry i cant follow ajv for this need some one with more experiences.

**Comment by francisbrito** [comment]
Thanks for letting me look over!

Does this API look good to you? @mhf-ir @mcollina 
```js
const schema = {
  type: "array",
  separator: ",",
  items: {
    type: "number"
  }
};
```

The idea is that if `separator` keyword is present the input will be parsed as a string-separated-list

**Pull request closed without merging**
