### PR TITLE
Avoid value of for fluent-schema

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by mcollina** [comment]
> Could valueOf called twice?

No. Why?

**Comment by allevo** [comment]
So, is this a breaking change?

**Comment by mcollina** [comment]
No. Why would it be? How does it relate to valueOf being called twice? I’m kind of lost on your arguments, would you mind making an example?

**Comment by allevo** [comment]
Never mind, I'm sorry.
```js
  if (opts.schema && opts.schema[Symbol.for('fluent-schema-object')]) {
    opts.schema = opts.schema.valueOf()
  }
```
This is the check I don't see before.

**Pull request merged**
